### ISSUE TITLE
Update Timer parameter doesn't apply to Markdown files

### ISSUE THREAD

**Issue by cameronpickham** [terrastruct/d2-vscode#111]
I'm including some D2 in a `.md` file and it is rendering correctly, but I can't find a way to make re-renders behave as they do with `.d2` files. It re-renders very frequently, mid-keystroke, which seems to hang and/or block keyboard input. Is it possible to have this property apply to `.md` files as well as `.d2` files, or should I handle this some other way?

**Comment by BarryNolte** [comment]
In VsCode, the extension 'in charge' of a file is based on the file extension, which is why our preview update speed (1.5 seconds from the last keystroke, adjustable via preferences) works with .d2 files, since we're 'in charge' of it.  In a markdown file, the built in (or external) extension is responsible for update speed.  We only get involved in the markdown file when it finds an embedded 'thing' that it can ask someone else to render.

I can't find a setting in the markdown preferences to change the update speed, or lag from the last keystroke.

**Comment by BarryNolte** [comment]
@cameronpickham Can I close this? There's nothing we can do about it, but you could open an issue against the markdown extension as a feature request.

**Comment by cameronpickham** [comment]
Sorry, yes! Thank you for the response 😄
