### ISSUE TITLE
Detection of d2 on WSL

### ISSUE THREAD

**Issue by FabienSe** [terrastruct/d2-vscode#90]
Hello,

I am using VS Code to open a project on WSL thanks to official WSL extension.

I installed d2 on WSL with the provided command:

```console
curl -fsSL https://d2lang.com/install.sh | sh -s --
```

The command is in the path since I can call it from the terminal:

```console
> d2 --version
v0.4.1
```

But the d2 extension provide the following error:

```console
[11:29:34] - ************************************************************
[11:29:34] - D2 executable not found.
[11:29:34] - Make sure the D2 executable is installed and on your system PATH.
[11:29:34] - https://d2lang.com/tour/install
[11:29:34] - ************************************************************
[11:35:51] - Preview for test.d2 has errors.
```

In the preview, I have the following error: `spawnSync d2 ENOENT`

Is WSL is officially supported by the extension ? If not, is it possible to add the support ?

I really like d2 and I would like to use it on WSL.

Thanks a lot for your help.

**Comment by alixander** [comment]
perhaps we could add the default WSL installation path to where vscode searches for executables? not sure if it works that way, cc @BarryNolte

**Comment by BarryNolte** [comment]
@alixander I'm sure it's simple case.  Extensions aren't supposed to know where they're running, and this is I think one of two places I distinguish between windows/not windows.

**Comment by BarryNolte** [comment]
@FabienSe 
Can you check on your install:
1. D2 is installed within your WSL distro and on the path.
2. D2-Vscode Extension is installed on the remote server vs locally.

I hate to say it, but given those two conditions being true, "it works on my machine".  But then again, this is the first time I tried this, so I might be missing something.

**Comment by dired** [comment]
I had exactly this problem and found the" way to make it work:
Install vscode wsl extension -> Reopen folder in wsl -> d2-command can be found (if you have left it as d2 in the d2-extension-settings)
[Documentation related to vscode and wsl: https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode]

Otherwise I extpected it would work by setting the command right in the d2-extension-settings. Normally from cmd or powershell, a wsl command can be executed like that: `wsl -ls -la`. When I tried in powershell/cmd, `wsl d2` didnt work, but `wsl /home/user/.local/bin/d2` did (just to confirm). But in the extension settings, setting the d2 command to `wsl /home/user/.local/bin/d2` -> does not work, it still gives "spawnSync wsl /home/user/.local/bin/d2 ENOENT".

As it works with the vscode-wsl-extension, for me this is solved, if it is a bug that giving the actually correct command (`wsl /home/user/.local/bin/d2`) I cannot judge.

**Comment by BarryNolte** [comment]
It sounds like you don't have the vscode D2 extension installed on the remote system (wsl in this case).  While you can run linux commands through the wsl command line tool, it breaks the vscode model of remote vs. local execution.

**Comment by BarryNolte** [comment]
I believe this is resolved now.

**Comment by mathisgauthey** [comment]
Hey there, to add up to what's been said here, I needed to restart VS Code as well.  

To sum up:  

1. **D2 is installed within your WSL distro and on the path.**  
   Here’s the installation script I used:  

   ```bash
   #!/bin/zsh

   set -e

   # Fetch and execute the D2 install script
   curl -fsSL https://d2lang.com/install.sh | sh -s --

   # Add D2 to PATH if not already present
   for rcfile in ~/.zshrc ~/.bashrc; do
     if ! grep -q 'export PATH="$HOME/.local/bin:$PATH"' "$rcfile"; then
       echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$rcfile"
     fi

     # Add D2 man pages to MANPATH
     if ! grep -q 'export MANPATH="$HOME/.local/share/man:$MANPATH"' "$rcfile"; then
       echo 'export MANPATH="$HOME/.local/share/man:$MANPATH"' >> "$rcfile"
     fi
   done

   # Reload shell configuration
   source ~/.zshrc

   # Verify installation
   d2 --version
   ```

2. **D2-VS Code Extension is installed on the remote server vs locally.**  
   Just double-check that it’s installed on the correct environment.
